// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/store","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"店铺管理","path":"/store","icon":"HomeOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"分类管理","path":"/category","icon":"AppstoreOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"404","path":"*","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"4"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Store__index" */'@/pages/Store/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Category__index" */'@/pages/Category/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "nm___creekjs__web-components__dist__creek-layout__Exception__NotFoundPage" */'/Users/ernestwang/Documents/code-resoorce/creek/node_modules/.pnpm/@creekjs+web-components@1.0.3_@types+react@18.3.27_antd@5.29.1_date-fns@2.30.0_moment@2.30.1__2blq3edrdl4kmkbflyfpuotdhu/node_modules/@creekjs/web-components/dist/creek-layout/Exception/NotFoundPage.js')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-creekLayout__Layout" */'/Users/ernestwang/Documents/code-resoorce/creek/packages/create-creek/templates/default/src/.umi/plugin-creekLayout/Layout.tsx')),
},
  };
}
