// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {CreekIcon} from '/Users/ernestwang/Documents/code-resoorce/creek/node_modules/.pnpm/@creekjs+web-components@1.0.3_@types+react@18.3.27_antd@5.29.1_date-fns@2.30.0_moment@2.30.1__2blq3edrdl4kmkbflyfpuotdhu/node_modules/@creekjs/web-components/dist/creek-icon/index.js';
import HomeOutlined from '/Users/ernestwang/Documents/code-resoorce/creek/packages/create-creek/templates/default/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import AppstoreOutlined from '/Users/ernestwang/Documents/code-resoorce/creek/packages/create-creek/templates/default/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
export default {CreekIcon,HomeOutlined, AppstoreOutlined,  };
