// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {CreekIcon} from '/Users/ernestwang/Documents/code-resoorce/creek/packages/web-components/dist/creek-icon/index.js';
import HomeOutlined from '/Users/ernestwang/Documents/code-resoorce/creek/apps/pc/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import AppstoreOutlined from '/Users/ernestwang/Documents/code-resoorce/creek/apps/pc/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
import ShoppingOutlined from '/Users/ernestwang/Documents/code-resoorce/creek/apps/pc/node_modules/@ant-design/icons/es/icons/ShoppingOutlined';
export default {CreekIcon,HomeOutlined, AppstoreOutlined, ShoppingOutlined,  };
