// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { useLocation, useAppData, IRoute, matchRoutes, Outlet, useNavigate } from 'umi';
import { useMemo } from 'react';
import _ from 'lodash';
import { CreekLayout, CreekLayoutProps } from '/Users/ernestwang/Documents/code-resoorce/creek/packages/create-creek/templates/default/node_modules/@creekjs/web-components';

import { useModel } from '@@/plugin-model';

import { useAccessMarkedRoutes } from '@@/plugin-access';

// 过滤出需要显示的路由, 这里的filterFn 指 不希望显示的层级
const filterRoutes = (routes: IRoute[], filterFn: (route: IRoute) => boolean) => {
  if (routes.length === 0) {
    return [];
  }
  let newRoutes = [];
  for (const route of routes) {
    const newRoute = { ...route };
    if (filterFn(route)) {
      if (Array.isArray(newRoute.routes)) {
        newRoutes.push(...filterRoutes(newRoute.routes, filterFn));
      }
    } else {
      if (Array.isArray(newRoute.children)) {
        newRoute.children = filterRoutes(newRoute.children, filterFn);
        newRoute.routes = newRoute.children;
      }
      newRoutes.push(newRoute);
    }
  }

  return newRoutes;
};

// 格式化路由 处理因 wrapper 导致的 菜单 path 不一致
const mapRoutes = (routes: IRoute[]) => {
  if (routes.length === 0) {
    return [];
  }
  return routes.map((route) => {
    // 需要 copy 一份, 否则会污染原始数据
    const newRoute = { ...route };
    if (route.originPath) {
      newRoute.path = route.originPath;
    }

    if (Array.isArray(route.routes)) {
      newRoute.routes = mapRoutes(route.routes);
    }

    if (Array.isArray(route.children)) {
      newRoute.children = mapRoutes(route.children);
    }

    return newRoute;
  });
};

const Layout = (props: CreekLayoutProps) => {
  const location = useLocation();
  const navigate = useNavigate();
  const { clientRoutes, pluginManager } = useAppData();
  const initialInfo = (useModel && useModel('@@initialState')) || {
    initialState: undefined,
    loading: false,
    setInitialState: null,
  };
  const userConfig = {
  "title": "creekjs",
  "iconFontCNs": [
    "//at.alicdn.com/t/c/font_4756000_mbo4n1jtw7m.js"
  ]
};
  const creekLocaleConfig = undefined;
  const runtimeConfig = pluginManager.applyPlugins({
    key: 'layout',
    type: 'modify',
    initialValue: {
      ...initialInfo,
    },
  });

  // 现在的 layout 及 wrapper 实现是通过父路由的形式实现的, 会导致路由数据多了冗余层级
  const newRoutes = filterRoutes(
    clientRoutes.filter((route) => route.id === 'ant-design-pro-layout'),
    (route) => {
      return (
        (!!route.isLayout && route.id !== 'ant-design-pro-layout') || !!route.isWrapper
      );
    }
  );
  const [route] = useAccessMarkedRoutes(mapRoutes(newRoutes));

  const matchedRoute = useMemo(
    () => matchRoutes(route.children, location.pathname)?.pop?.()?.route,
    [location.pathname]
  );

  return (
      <CreekLayout
        location={location}
        runtimeConfig={runtimeConfig}
        matchedRoute={matchedRoute}
        navigate={navigate}
        userConfig={userConfig}
        route={route}
        initialInfo={initialInfo}
        children={
          runtimeConfig.childrenRender ? (
            runtimeConfig.childrenRender(<Outlet />, props)
          ) : (
            <Outlet />
          )
        }
      />
  );
};

export default Layout;
