// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import type { ProLayoutProps, HeaderProps } from '@ant-design/pro-components';
     import type InitialStateType from '@@/plugin-initialState/@@initialState';
     type InitDataType = ReturnType<typeof InitialStateType>; 
    import type { IConfigFromPlugins } from '@@/core/pluginConfig';

    export type RunTimeLayoutConfig = (initData: InitDataType) => ProLayoutProps & {
      dropdownProps?: DropDownProps;
      showDarkButton?: boolean;
      showFooter?: boolean;
      provider?:  React.ReactNode;
      userName?: string;
      hideKeepalive?: boolean;
      rightContentExtra?: React.ReactNode;
      childrenRender?: (dom: JSX.Element, props: ProLayoutProps) => React.ReactNode;
      unAccessible?: JSX.Element;
      logout?: (initialState: InitDataType['initialState']) => Promise<void> | void;
      iconFontCNs?: string[];
      rightRender?: (
        initialState: InitDataType['initialState'],
        setInitialState: InitDataType['setInitialState'],
        runtimeConfig: RunTimeLayoutConfig,
      ) => JSX.Element;
      
    };
